# Copyright (C) 2011-2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/s7/extract-files.sh

# Proprietary bin files
PRODUCT_COPY_FILES += \
    vendor/huawei/s7/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/huawei/s7/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/s7/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/huawei/s7/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/s7/proprietary/bin/ntfs-3g:system/bin/ntfs-3g \
    vendor/huawei/s7/proprietary/bin/qmuxd:system/bin/qmuxd \
# Proprietary etc files
PRODUCT_COPY_FILES += \
    vendor/huawei/s7/proprietary/etc/init.bt.sh:system/etc/init.bt.sh \
    vendor/huawei/s7/proprietary/etc/init.brcm.bt.sh:system/etc/init.brcm.bt.sh \
    vendor/huawei/s7/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/huawei/s7/proprietary/etc/nv.bin:system/etc/nv.bin \
    vendor/huawei/s7/proprietary/etc/wifi/rtecdc-bcm4329.bin:system/etc/wifi/rtecdc-bcm4329.bin \
    vendor/huawei/s7/proprietary/etc/wifi/nvram_mfgtest-bcm4329.txt:system/etc/wifi/nvram_mfgtest-bcm4329.txt \
    vendor/huawei/s7/proprietary/etc/wifi/nvram-bcm4329.txt:system/etc/wifi/nvram-bcm4329.txt \
    vendor/huawei/s7/proprietary/etc/wifi/rtecdc-apsta-bcm4329.bin:system/etc/wifi/rtecdc-apsta-bcm4329.bin \
   vendor/huawei/s7/proprietary/etc/wifi/rtecdc-mfgtest-bcm4329.bin:system/etc/wifi/rtecdc-mfgtest-bcm4329.bin \
    vendor/huawei/s7/proprietary/etc/wifi/rtecdc-bcm4319.bin:system/etc/wifi/rtecdc-bcm4319.bin \
    vendor/huawei/s7/proprietary/etc/wifi/nvram_mfgtest-bcm4319.txt:system/etc/wifi/nvram_mfgtest-bcm4319.txt \
    vendor/huawei/s7/proprietary/etc/wifi/nvram-bcm4319.txt:system/etc/wifi/nvram-bcm4319.txt \
    vendor/huawei/s7/proprietary/etc/wifi/rtecdc-apsta-bcm4319.bin:system/etc/wifi/rtecdc-apsta-bcm4319.bin \
    vendor/huawei/s7/proprietary/etc/wifi/rtecdc-mfgtest-bcm4319.bin:system/etc/wifi/rtecdc-mfgtest-bcm4319.bin \
    vendor/huawei/s7/proprietary/etc/wifi/wpa_supplicant.conf:system//etc/wifi/wpa_supplicant.conf \
    vendor/huawei/s7/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/huawei/s7/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/huawei/s7/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/huawei/s7/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/s7/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/huawei/s7/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/huawei/s7/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/huawei/s7/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/huawei/s7/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/huawei/s7/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/huawei/s7/proprietary/etc/bluetooth/BCM4329B1_002.002.023.0313.0390.hcd:system/etc/bluetooth/BCM4329B1_002.002.023.0313.0390.hcd \
    vendor/huawei/s7/proprietary/etc/loc_parameter.ini:obj/etc/loc_parameter.ini \
# Proprietary lib files
PRODUCT_COPY_FILES += \
    vendor/huawei/s7/proprietary/lib/liba2dp.so:obj/lib/liba2dp.so \
    vendor/huawei/s7/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
    vendor/huawei/s7/proprietary/lib/libauth.so:obj/lib/libauth.so \
    vendor/huawei/s7/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/huawei/s7/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/s7/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/s7/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/s7/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/s7/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/huawei/s7/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/huawei/s7/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/huawei/s7/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/s7/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/huawei/s7/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/huawei/s7/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/s7/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/huawei/s7/proprietary/lib/libloc-rpc.so:system/lib/libloc-rpc.so \
    vendor/huawei/s7/proprietary/lib/libloc.so:system/lib/libloc.so \
    vendor/huawei/s7/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/huawei/s7/proprietary/lib/libloc_api.so:system/lib/libloc_api.so \
    vendor/huawei/s7/proprietary/lib/libgps.so:system/lib/libgps.so \
    vendor/huawei/s7/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/s7/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/huawei/s7/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/s7/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/s7/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/huawei/s7/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/huawei/s7/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/huawei/s7/proprietary/lib/libOmxVdec.so:system/lib/libOmxVdec.so \
    vendor/huawei/s7/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/huawei/s7/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/s7/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/huawei/s7/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/huawei/s7/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/huawei/s7/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/s7/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/s7/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/s7/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/huawei/s7/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/s7/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/s7/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/s7/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/s7/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/s7/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/s7/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/s7/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/s7/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/s7/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/s7/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/s7/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/s7/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/s7/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/s7/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/s7/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/s7/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/s7/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/huawei/s7/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
# Proprietary usr files
PRODUCT_COPY_FILES += \
    vendor/huawei/s7/proprietary/usr/idc/t1320.idc:system/usr/idc/t1320.idc \
    vendor/huawei/s7/proprietary/usr/idc/cypress120-i2c-touchscreen-ere.idc:system/usr/idc/cypress120-i2c-touchscreen-ere.idc \
    vendor/huawei/s7/proprietary/usr/keychars/s7_keypad.kcm.bin:system/usr/keychars/s7_keypad.kcm.bin \
    vendor/huawei/s7/proprietary/usr/keylayout/s7_handset.kl:system/usr/keylayout/s7_handset.kl \
    vendor/huawei/s7/proprietary/usr/keylayout/s7_keypad.kl:system/usr/keylayout/s7_keypad.kl \
    vendor/huawei/s7/proprietary/usr/keylayout/cypress120-i2c-touchscreen-ere.kl:system/usr/keylayout/cypress120-i2c-touchscreen-ere.kl \
# Proprietary apk files
PRODUCT_COPY_FILES += \
    vendor/huawei/s7/proprietary/media/bootanimation.zip:system/media/bootanimation.zip \
    vendor/huawei/s7/proprietary/app/Apexlauncher.apk:system/app/Apexlauncher.apk \
    vendor/huawei/s7/proprietary/app/RootExplorer.apk:system/app/RootExplorer.apk \
